name: CI
on:
  pull_request:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:
jobs:
  linter:
    name: Run linting and format code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GIT_TOKEN }}
      - uses: styfle/cancel-workflow-action@0.10.0
        with:
          all_but_latest: true
          access_token: ${{ secrets.GIT_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 17
      - name: Get yarn cache
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run format
        run: yarn run format
      - uses: illvart/beautysh-action@latest
        with:
          args: '*.sh --indent-size 2 &>/dev/null'
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '[action] ci: auto-fixes'
          commit_options: '--no-verify'
          commit_user_name: notudope
          commit_user_email: notudope@gmail.com
          commit_author: notudope <notudope@gmail.com>